### ISSUE TITLE
useBuiltIns的例子问题

### ISSUE THREAD

**Issue by oopsman** [Shenfq/studyBabel#1]
useBuiltIns的例子是箭头函数  感觉不会用到ployfill吧  只会用到synax转化而已 ？
但不清楚为什么useBuiltIns的值不同 导致最后的文件大小不同？  /7-babel-env/

**Comment by Shenfq** [comment]
使用babel-preset-env会自动引入polyfill，useBuiltIns会根据target的配置去除掉那些不必要的polyfill

**Comment by oopsman** [comment]
使用babel-preset-env会自动引入polyfill???  如果自动引入polyfill  那在src.js还需要手动import polyfill？？？

**Comment by Chang1ng** [comment]
不是已经按需引入了吗，为啥还会差70kb?不科学吧

**Comment by Shenfq** [comment]
现在已经使用 babel7 了，这篇文章有些观点已经过时，建议阅读 babel7 官方文档。另外前面没有说过已经按需引入吧？
